feat: support com_query insert sql request
CECTC/dbpack pull request #129
Opened 2022-06-05 08:40 UTC by wybrobin

ref: https://github.com/cectc/dbpack/issues/<issueID>

### Ⅰ. Describe what this PR did
support com_query insert sql request

### Ⅱ. Does this pull request fix one issue?
https://github.com/CECTC/dbpack/issues/104

### Ⅲ. Why don't you add test cases (unit test/integration test)? 
Added

### Ⅳ. Describe how to verify it
Run insert sql in com_query

### Ⅴ. Special notes for reviews
No

2022-06-05 13:01 UTC, fatelei commented
LGTM

2022-06-06 02:06 UTC, dk-lockdown commented on pkg/filter/dt/exec/query_insert.go
> +		for _, column := range allColumns {
```suggestion
		for i, column := range allColumns {
```

2022-06-06 02:06 UTC, dk-lockdown commented on pkg/filter/dt/exec/query_insert.go
> +				return idx
```suggestion
				return i
```

2022-06-06 02:06 UTC, dk-lockdown commented on pkg/filter/dt/exec/query_insert.go
> +			idx = idx + 1
```suggestion
```

2022-06-06 02:06 UTC, dk-lockdown commented on pkg/misc/sql.go
> +		fmt.Fprintf(&sb, "'%v'", value)
if pk type is `[]byte`, there will cause an exception

2022-06-06 11:16 UTC, bohehe requested changes

2022-06-06 11:16 UTC, bohehe commented on pkg/filter/dt/exec/query_insert.go
> +	if insertColumns != nil && len(insertColumns) > 0 {
```suggestion
	if len(insertColumns) > 0 {
```

2022-06-07 02:16 UTC, dk-lockdown commented on pkg/filter/dt/exec/query_insert.go
> +		var idx = 0
```suggestion
```

2022-06-07 02:16 UTC, dk-lockdown commented on pkg/filter/dt/exec/query_insert.go
> +		i = i + 1
```suggestion
```

2022-06-07 02:16 UTC, dk-lockdown commented on pkg/filter/dt/exec/query_insert.go
> +		if i < columnCount {
```suggestion
		if i < columnCount-1 {
```

2022-06-07 02:16 UTC, dk-lockdown commented on pkg/filter/dt/exec/query_insert.go
> +	for _, column := range tableMeta.Columns {
```suggestion
	for i, column := range tableMeta.Columns {
```

2022-06-07 02:16 UTC, dk-lockdown commented on pkg/filter/dt/exec/query_insert.go
> +	var i = 0
```suggestion
```

2022-06-07 02:16 UTC, dk-lockdown commented on pkg/filter/dt/exec/query_insert.go
> +	if insertColumns != nil {
```suggestion
	if len(insertColumns) > 0 {
```

2022-06-07 02:46 UTC, dk-lockdown approved these changes

2022-06-07 02:47 UTC, merged