feat: audit log filter
CECTC/dbpack pull request #155
Opened 2022-06-14 07:44 UTC by dk-lockdown

ref: https://github.com/cectc/dbpack/issues/103

### Ⅰ. Describe what this PR did
AuditLog Format:
```
[timestamp],[username],[ip address],[connection id],[command type],[command],[sql text],[args],[affected row]
``` 
command type has only two values: `COM_QUERY`、`COM_STMT_EXECUTE`.
command has five values: `INSERT`、`DELETE`、`UPDATE`、`SELECT` and empty
only when command type is `COM_STMT_EXECUTE`, args have value.

### Ⅱ. Does this pull request fix one issue?

### Ⅲ. Why don't you add test cases (unit test/integration test)? 

### Ⅳ. Describe how to verify it

### Ⅴ. Special notes for reviews

2022-06-21 13:22 UTC, adofsauron commented
LGTM

2022-06-23 14:17 UTC, bohehe requested changes
Sorry to post massive comments... can you please check accordingly? Thank you.

2022-06-23 14:17 UTC, bohehe commented on docker/conf/config_sdb.yaml
> +      max_size: 300
Leave a comment here like "MB" or "GB"?

2022-06-23 14:17 UTC, bohehe commented on docker/conf/config_sdb.yaml
> +      max_age: 28
28 days?

2022-06-23 14:17 UTC, bohehe commented on pkg/filter/audit_log/filter.go
> +		filterConfig.MaxSize = 500
use a constant to represent for 500, e.g. defaultMaxSize

2022-06-23 14:17 UTC, bohehe commented on pkg/filter/audit_log/filter.go
> +		filterConfig.MaxBackups = 1
use a constant.

2022-06-23 14:17 UTC, bohehe commented on pkg/filter/audit_log/filter.go
> +		filterConfig.MaxAge = 30
use a constant

2022-06-23 14:17 UTC, bohehe commented on docker/conf/config_sdb.yaml
> +    conf:
Why not add other configs here, like "record_before", "compress"...
It would be better if we can provide full configurations here.

2022-06-23 14:17 UTC, bohehe commented on pkg/filter/audit_log/filter.go
> +	var stmt ast.Node
```suggestion
	var (
	    commandTypeStr string
	    args strings.Builder
	    stmt ast.Node
	)
```

2022-06-23 14:44 UTC, bohehe commented on pkg/filter/audit_log/filter.go
> +	RecordBefore bool `json:"record_before" yaml:"record_before"`
Can you please also comment for `RecordBefore `?

2022-06-23 14:44 UTC, bohehe approved these changes
LGTM

2022-06-23 14:59 UTC, merged